# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='direccion_sucursal',
            new_name='direccion',
        ),
    ]
