# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
        ('usuario', '0003_remove_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='direccion.Telefono', verbose_name='telefono'),
            preserve_default=False,
        ),
    ]
