# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptante', '0004_remove_persona_usuario'),
        ('usuario', '0005_usuario_adoptante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='adoptante',
        ),
        migrations.AddField(
            model_name='usuario',
            name='adoptante',
            field=models.ManyToManyField(related_name='adoptante_usuario', to='adoptante.Persona'),
        ),
    ]
