# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20161202_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='adoptante',
            field=models.ManyToManyField(related_name='adoptante_usuario', to='adoptante.Solicitud'),
        ),
    ]
