# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20161202_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='adoptante',
        ),
    ]
