# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoptante', '0004_remove_persona_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_persona', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
