# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
        ('adoptante', '0005_persona_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='persona_direccion', to='direccion.Direccion'),
            preserve_default=False,
        ),
    ]
