# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoptante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Infante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('educacion', models.ManyToManyField(blank=True, null=True, to='infante.Educacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoptante.Persona')),
            ],
            options={
                'verbose_name_plural': 'Mascotas',
                'verbose_name': 'Mascota',
            },
        ),
    ]
