# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infante',
            options={'verbose_name': 'Infante', 'verbose_name_plural': 'Infantes'},
        ),
    ]
