# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infante', '0002_auto_20161202_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infante',
            name='educacion',
            field=models.ManyToManyField(to='infante.Educacion'),
        ),
    ]
